events { worker_connections 1024; }



http {

    # Hardening: Hide Nginx version from attackers

    server_tokens off;



    server {

        listen 80;



        location / {

            root /usr/share/nginx/html;

            index index.html index.htm;



            # Security Header: Prevent MIME-type sniffing

            add_header X-Content-Type-Options nosniff;

        }

    }

}
